### ISSUE TITLE
VMware Workstation (application) icon needed

### ISSUE THREAD

**Issue by comxd** [NitruxSA/flattr-icons#103]
+ VMware player.

**Comment by crutchcorn** [comment]
Here here! @UriHerrera, do you need more info about this at all?

**Comment by UriHerrera** [comment]
There is two icons for VMware: vmware and vmware-workstation. I'm guessing neither of them are used by the .desktop file if there is one.

So: Are they used by the software launcher? or is the launcher manually created.

**Comment by crutchcorn** [comment]
Launcher is not manually created by the user. When the installer is ran, it simply shows the VMware icon in the launcher. I can grab you the files if at all possible.

**Comment by UriHerrera** [comment]
Yes add the launcher infomartion here.

**Comment by crutchcorn** [comment]
[Linux] VMware Workstation Gnome 3.14

[Desktop Entry]
Encoding=UTF-8
Name=VMware Workstation
Comment=Run and manage virtual machines
Exec=/usr/bin/vmware %U
Terminal=false
Type=Application
Icon=vmware-workstation
StartupNotify=true
Categories=System;
MimeType=application/x-vmware-vm;application/x-vmware-team;application/x-vmware-enc-vm;x-scheme-handler/vmrc;


And 

[Linux] VMware Player Gnome 3.14

[Desktop Entry]
Encoding=UTF-8
Name=VMware Player
Comment=Run a virtual machine
Exec=/usr/bin/vmplayer %u
Terminal=false
Type=Application
Icon=vmware-player
StartupNotify=true
Categories=System;
MimeType=application/x-vmware-vm;application/x-vmware-enc-vm;x-scheme-handler/vmrc;
