### ISSUE TITLE
Other icon sizes

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#106]
In the case of folder, application, and mimetype icons, other sizes (e.g. 22, 24, and 48) are necessary; see the screenshots below for examples.

![screenshot from 2015-01-20 11 32 01](https://cloud.githubusercontent.com/assets/8833323/5821221/4af3c316-a098-11e4-8d8e-2d93776e2fc4.png)
![screenshot from 2015-01-20 11 32 42](https://cloud.githubusercontent.com/assets/8833323/5821224/4d365300-a098-11e4-93c1-8be40b19b944.png)
![screenshot from 2015-01-20 11 32 54](https://cloud.githubusercontent.com/assets/8833323/5821229/4f2891dc-a098-11e4-957f-cc89ff4888ce.png)

**Comment by UriHerrera** [comment]
I presume this is mostly because the icons are set to a *fixed* size in the index.theme. Since I'm using KDE and KDE scales them correctly this doesn't happen.

Just have to change the lines in the file.
