### ISSUE TITLE
[Linux] dconf Editor, GNOME (dconf-editor)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#108]
An application icon for dconf Editor is needed. Its icon name is `dconf-editor`.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by crutchcorn** [comment]
[Linux] dconf Editor Gnome
[Desktop Entry]
Name=dconf Editor
Comment=Directly edit your entire configuration database
Keywords=settings;configuration;
Exec=dconf-editor
Terminal=false
Type=Application
Icon=dconf-editor
StartupNotify=true
Categories=GNOME;GTK;System;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=dconf
X-GNOME-Bugzilla-Component=editor
X-GNOME-Bugzilla-Version=0.20.0
X-Ubuntu-Gettext-Domain=dconf
