### ISSUE TITLE
[Linux] Document Viewer, GNOME (evince)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#109]
An application icon for Document Viewer is needed. Its icon name is `evince`.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by crutchcorn** [comment]
[Desktop Entry]
Name=Document Viewer
Comment=View multi-page documents
Keywords=pdf;ps;postscript;dvi;xps;djvu;tiff;document;presentation;
TryExec=evince
Exec=evince %U
StartupNotify=true
Terminal=false
Type=Application
Icon=evince
X-GNOME-DocPath=
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=evince
X-GNOME-Bugzilla-Component=BugBuddyBugs
X-GNOME-Bugzilla-Version=3.10.3
Categories=GNOME;GTK;Office;Viewer;Graphics;2DGraphics;VectorGraphics;
MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-dvi;application/x-bzdvi;application/x-gzdvi;image/vnd.djvu;image/tiff;application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/oxps;application/vnd.ms-xpsdocument;
X-Ubuntu-Gettext-Domain=evince
