### ISSUE TITLE
[Linux] Geary, GNOME (geary)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#110]
An application icon for Geary is needed. Its icon name is `geary`. It is an email application used by default on elementary OS.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by UriHerrera** [comment]
Icon already present.
