### ISSUE TITLE
[Linux] LibreOffice Writer, GNOME (libreoffice-writer)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#113]
An application icon for LibreOffice Writer is needed. Its icon name is `libreoffice-writer`.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by UriHerrera** [comment]
As I don't want to have the same issue of the previous icons of just adding the LO logo on a background, LO icons will be links to those of Calligra, which are distinctive.
