### ISSUE TITLE
[Linux] Pinta, GNOME (pinta)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#114]
An application icon for Pinta is needed. Its icon name is `pinta`. It is a drawing application, similar to but much simpler than Krita.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by UriHerrera** [comment]
A link to Krita should do.
