### ISSUE TITLE
[Linux] Simple Scan, GNOME (scanner)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#115]
An application icon for Simple Scan is needed. Its icon name is `scanner`.

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by UriHerrera** [comment]
They should really change their app icon to an actual app icon and not a device.

**Comment by UriHerrera** [comment]
I'm labeling it as missing-icon because it's indeed missing a scanner device icon, but, the icon simple scan uses is wrong.
