### ISSUE TITLE
[Linux] systemadm, GNOME (applications-system)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [NitruxSA/flattr-icons#116]
An application icon for systemadm is needed. Its icon name is `applications-system`. It is a `systemd` unit manager; its interface looks like [this](https://cloud.githubusercontent.com/assets/8833323/5821371/98515852-a099-11e4-8e96-7ece34cffc9e.png).

![screenshot from 2015-01-20 11 28 56](https://cloud.githubusercontent.com/assets/8833323/5821262/8d267cd8-a098-11e4-90ef-720cf259e9bf.png)

**Comment by UriHerrera** [comment]
The icons is wrong, it shouldn't be using app icons from other folders like categories (where the icon it's requesting goes). Please tell upstream to change it.
