### ISSUE TITLE
Icons not properly applied to some groups

### ISSUE THREAD

**Issue by Aeolus0** [NitruxSA/flattr-icons#123]
In the sidebar of Nemo, the home and SMB small icons are not applied properly
![icons](https://cloud.githubusercontent.com/assets/4737200/5960662/ee79658c-a78b-11e4-84ff-1bd11b7fab59.png)

See screenshot

**Comment by UriHerrera** [comment]
The icons show up on my freshly installed Mint VM.

![](http://i.imgur.com/40dJCvq.png)

**Comment by Aeolus0** [comment]
Successfully recreated bug in Liveusb environment. (Mint 17 64-bit Cinnamon)
Note: flattr-icons from commit fd7ef71 works fine

![screenshot from 2015-01-30 02 05 10](https://cloud.githubusercontent.com/assets/4737200/5970086/345058d8-a825-11e4-8c48-eeec5a165b77.png)

**Comment by UriHerrera** [comment]
Cinnamon seemingly changed what icons it uses for the sidebar on Mint 17.1

In version 2.4.5 it uses the standard named icons, apparently in older versions it used other icons.

![](http://i.imgur.com/eh8DKAb.png)

**Comment by UriHerrera** [comment]
I recommend you to upgrade your OS or at least Cinnamon.
