### ISSUE TITLE
Missing icons in KDE

### ISSUE THREAD

**Issue by NerosTie** [NitruxSA/flattr-icons#124]
Hello,
Some missing icons since 1.0:

worplace behavior
preferences *
warning sign
activities
flash player
kile
kdevelop4
OTR
video call
(icons in ktp telepathy)
calendar (in kontact)
kmail notification

And:
redshift
kamoso

And maybe others..

Is it planned to add them?
(I'm using "inherits" with the previous version of flattr for missing icons, it works well)

Great update! I like it! But not complete for a KDE user.

Thanks :)

**Comment by UriHerrera** [comment]
Please read [Reporting missing icons](https://github.com/NitruxSA/flattr-icons#reporting-missing-icons) and update your issue accordingly. Thanks!.
