### ISSUE TITLE
[Linux] Shutdown indicator Unity

### ISSUE THREAD

**Issue by pahofmann** [NitruxSA/flattr-icons#147]
There is no Icon for the indicator with the shutdown menu.
The color of the clock is fine, but the other colors are so light you can barely see them.
![selection_003](https://cloud.githubusercontent.com/assets/5699104/7519736/5b27991c-f4e2-11e4-9648-5e51f6d6cd1d.png)

**Comment by UriHerrera** [comment]
There's already light icons in the theme, they're not in the *released* TARs and they're not included in the folder structure to use them but they're there. OF course, the icons being **dark**  means that they're meant to be used with a light theme.

**Comment by pahofmann** [comment]
Oh okay sounds logical. What aboout the missing icon though?

**Comment by UriHerrera** [comment]
I'll add it.
