### ISSUE TITLE
Battery charging at 100% - Ubuntu

### ISSUE THREAD

**Issue by anaturinbor** [NitruxSA/flattr-icons#152]
The battery charging icons on Unity have been fixed recently except for when the battery is charging at 100%.

![2](https://cloud.githubusercontent.com/assets/10692755/8185811/244b09f6-144f-11e5-8f83-7dc79a904ec7.png)

**Comment by UriHerrera** [comment]
This is an issue with Unity: https://github.com/NitruxSA/nitrux-icons/issues/71
