### ISSUE TITLE
[Windows] Remove SVG Background ? 

### ISSUE THREAD

**Issue by XenocodeRCE** [NitruxSA/flattr-icons#153]
**Please** read. I mean, Ok I'm under Windows but that does not make me a monster, does it ?

Anyway :smile: 

So I'm trying to customize my Windows OS (Yes it's possible) but all your SVG file has a white background and it literally kills the **Flattr* look 

![](http://i.imgur.com/Yw7VbvY.png)

Yet, you have to know that I converted every Flattr svg file into .ico file. So If you remove the white background I'll make a tar.gz archive for Windows users

**Comment by UriHerrera** [comment]
The background is transparent :O

**Comment by XenocodeRCE** [comment]
Oh dear ... yes my bad :disappointed: My fault, again :sob:
