### ISSUE TITLE
Xnoise panel symbolic icon is needed

### ISSUE THREAD

**Issue by sergioad** [NitruxSA/flattr-icons#93]
Hello @UriHerrera can you make a Xnoise panel symbolic icon?

icon=xnoise-panel

![xnoise-panel](https://cloud.githubusercontent.com/assets/5375145/5225304/3ae2ab0a-76a8-11e4-975e-438ac93e8676.png)

please add it soon as possible, before the official Manjaro's final release if you can you only need to take the X symbol :smile:

**Comment by UriHerrera** [comment]
> Xnoise development has come to an end, because there is no developer working on this program.

We thrive to support only maintained software.

**Comment by sergioad** [comment]
@UriHerrera Ok, I will need to switch from my default player now :smile:
