### ISSUE TITLE
[Linux] Battery icons missing XFCE, Unity, LXDE

### ISSUE THREAD

**Issue by Mulder90** [NitruxSA/flattr-icons#98]
Hi, thanks for the amazing icons. I have a problem with the battery icon on xubuntu 14.04 that isn't displayed correctly when the computer is charging.

Screen (charging):

![screenshot - 11122014 - 18 58 39](https://cloud.githubusercontent.com/assets/583497/5423887/de46a406-82d6-11e4-98ea-ea69b69014c7.png)

Screen (not charging):
![screenshot - 13122014 - 14 48 12](https://cloud.githubusercontent.com/assets/583497/5423901/2b152c62-82d7-11e4-8af3-bac270e5f3fe.png)

Thanks
Lorenzo

**Comment by Mulder90** [comment]
problem still present in version 1.0 :)

**Comment by UriHerrera** [comment]
There's no battery icons yet, yeah.

**Comment by anaturinbor** [comment]
I'm still having this problem on unity. The icons are not displayed when the battery is charging.

**Comment by UriHerrera** [comment]
That Unity uses symbolic icons **only** for the battery indicator is wrong. They can't certainly be links since symbolic icons are different in size, coloring and of course naming.

**Comment by anaturinbor** [comment]
Okay, thanks for the clarification.

**Comment by anaturinbor** [comment]
For the record I made links to the charging icons and it seems to be working fine for me.
![screenshot from 2015-04-02 17 23 46](https://cloud.githubusercontent.com/assets/10692755/6965902/6fe38910-d95d-11e4-8d0f-ee28f6d9f519.png)

**Comment by UriHerrera** [comment]
You linked to the symbolic ions? hmm. Maybe they changed it.
